theme = "nikhil"

[editor]
line-number = "relative"
mouse = false

[editor.statusline]
left = ["mode", "spinner","file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = false